// <auto-generated />
using System;
using CKCNNET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CKCNNET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CKCNNET.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameAccountId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameAccountId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("CKCNNET.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "MOBA game - Đấu Trường Chân Lý",
                            ImageUrl = "/images/lol.jpg",
                            Name = "League of Legends"
                        },
                        new
                        {
                            Id = 2,
                            Description = "MOBA game - Chiến Trường Quân Sư",
                            ImageUrl = "/images/dota2.png",
                            Name = "Dota 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "FPS game - Đấu súng chiến thuật",
                            ImageUrl = "/images/cs2.png",
                            Name = "Counter-Strike 2"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tactical shooter - Bắn súng chiến thuật",
                            ImageUrl = "/images/valorant.jpg",
                            Name = "Valorant"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Gacha RPG - Trò chơi nhập vai quay gacha",
                            ImageUrl = "/images/fgo.jpg",
                            Name = "FGO (Fate Grand Order)"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Gacha RPG - Nhập vai quay gacha chiến thuật",
                            ImageUrl = "/images/reverse1999.jpg",
                            Name = "Reverse: 1999"
                        },
                        new
                        {
                            Id = 7,
                            Description = "MMORPG - Trường Học Ninja",
                            ImageUrl = "/images/ninja_school.jpg",
                            Name = "Ninja School"
                        },
                        new
                        {
                            Id = 8,
                            Description = "MMORPG - Game nhập vai trực tuyến",
                            ImageUrl = "/images/hiep_si_online.jpg",
                            Name = "Hiệp Sĩ Online"
                        });
                });

            modelBuilder.Entity("CKCNNET.Models.GameAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("SellerId");

                    b.ToTable("GameAccounts");
                });

            modelBuilder.Entity("CKCNNET.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("GameAccountId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("CKCNNET.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Seller"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("CKCNNET.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountHolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSellerApproved")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankAccount = "1234567890",
                            BankAccountHolder = "Nguyen Van Admin",
                            CreatedAt = new DateTime(2026, 5, 5, 17, 34, 57, 446, DateTimeKind.Local).AddTicks(4443),
                            Email = "admin@gmail.com",
                            IsSellerApproved = true,
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            PhoneNumber = "0912345678",
                            RoleId = 3,
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("CKCNNET.Models.Cart", b =>
                {
                    b.HasOne("CKCNNET.Models.GameAccount", "GameAccount")
                        .WithMany("CartItems")
                        .HasForeignKey("GameAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CKCNNET.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GameAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CKCNNET.Models.GameAccount", b =>
                {
                    b.HasOne("CKCNNET.Models.Game", "Game")
                        .WithMany("GameAccounts")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CKCNNET.Models.User", "Seller")
                        .WithMany("GameAccounts")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("CKCNNET.Models.Purchase", b =>
                {
                    b.HasOne("CKCNNET.Models.User", "Buyer")
                        .WithMany("Purchases")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CKCNNET.Models.GameAccount", "GameAccount")
                        .WithMany("Purchases")
                        .HasForeignKey("GameAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("GameAccount");
                });

            modelBuilder.Entity("CKCNNET.Models.User", b =>
                {
                    b.HasOne("CKCNNET.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CKCNNET.Models.Game", b =>
                {
                    b.Navigation("GameAccounts");
                });

            modelBuilder.Entity("CKCNNET.Models.GameAccount", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("CKCNNET.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CKCNNET.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("GameAccounts");

                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
